---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Amazon DynamoDB - Users Table'

Parameters:
  Owner:
    Type: String
    Default: Josh Armitage
    Description: The Owner of the Resources

Resources:
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: email
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: users
      Tags:
        - Key: Owner
          Value: !Ref Owner
        - Key: Stack
          Value: Dev
        - Key: Project
          Value: Mech Rocking Kubernetes
